apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cort
  name: react-vite-app
  labels:
    app: react-vite-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels: 
        app: react-vite-app
    spec:
      containers:
      - name: react-vite-container
        image: cortlynd101/cort-react:${IMAGE_TAG}
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20